version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - static:/app/build

  gateway:
    build: ./nginx
    container_name: gateway
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media: